apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rfjo
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0027-tenant/tkrw-pr712-0075-0027-app/devfile-sample-rfjo@sha256:a3553519771f6a3b6ba92d09367f50307149efd031c68cf718b0275c0b83b5c7
        name: my-nodejs
        resources: {}
status: {}
